name: ci

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    ci:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [20]

        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 8

            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
                  cache: "pnpm"

            - run: pnpm install --frozen-lockfile

            - run: pnpm build
            - run: pnpm typecheck
            - run: pnpm lint
            - run: pnpm format
            - run: pnpm test

    e2e:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [20]

        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 8

            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}

            - run: pnpm install --frozen-lockfile
            - run: pnpm build

            - run: cd apps/www && pnpm test:e2e

            # - name: Run E2E tests
            #   uses: cypress-io/github-action@v6
            #   with:
            #       headed: true
            #       working-directory: apps/www
            #       browser: chrome
            #       build: pnpm build
            #       start: pnpm start
            #       wait-on: "http://localhost:3000"
