name: ci

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    ci:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [20]

        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 8

            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
                  cache: "pnpm"

            - run: pnpm install --prefer-offline --frozen-lockfile --prod
            - run: pnpm install turbo -w

            - run: pnpm build
            - run: pnpm typecheck
            - run: pnpm lint
            - run: pnpm format
            - run: pnpm test

    e2e:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [20]

        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 8

            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
                  cache: "pnpm"

            - run: pnpm install --prefer-offline --frozen-lockfile --prod
            - run: cd apps/www && cypress run --headed --browser chrome --spec 'cypress/e2e/**'
