name: ci

on:
    push:
    pull_request:
        branches:
            - main

jobs:
    ci:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ ubuntu-latest ]
                node: [ 16, 18 ]

        steps:
            -   uses: actions/checkout@v3
            -   uses: pnpm/action-setup@v2
                with:
                    version: 8
            -   uses: actions/setup-node@v3
                with:
                    node-version: ${{ matrix.node }}
                    cache: "pnpm"

            -   run: pnpm install
            -   run: pnpm typecheck
            -   run: pnpm lint
            -   run: pnpm build
            -   run: pnpm vitest run --coverage
